### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.megaglest.MegaGlest#2]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. The largest icon this currently contains is 48px.

There's an upstream PR for a 64x64px icon, but we'd need a 128x128 one ideally as well.
https://github.com/MegaGlest/megaglest-data/pull/19

**Comment by wjt** [comment]
https://flathub.org/apps/details/org.megaglest.MegaGlest seems to show the app
